services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: frontend
    env_file:
      - .env.development
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    networks:
      - app-network
    depends_on:
      - backend
    command: ['pnpm', 'dev']

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: backend
    env_file:
      - .env.development
    ports:
      - '${SERVER_PORT}:3000'
    depends_on:
      - postgres
    networks:
      - app-network
    command: [ 'pnpm', 'start:dev' ]

  postgres:
    image: postgres:17.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: